# Generated by Django 6.0.4 on 2026-04-15 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbvApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='passanger',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('travel_points', models.CharField(max_length=100)),
            ],
        ),
    ]
