# Generated by Django 6.0.4 on 2026-04-18 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightApp', '0002_alter_reservation_flight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='operatingAirlines',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
