# Generated by Django 6.0.4 on 2026-04-18 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightApp', '0003_alter_flight_operatingairlines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='operatingAirlines',
            field=models.CharField(max_length=100),
        ),
    ]
